### PR TITLE
Handle screencast frame acknowledge error

### LINKED ISSUE #12: Gracefully handle errors
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
      Error: Protocol error (Page.screencastFrameAck): Target closed.
          at /Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:123:63          at new Promise (<anonymous>)
          at CRSession.send (/Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:122:16)
          at CRSession.<anonymous> (/Users/jon/dev/qawolf/node_modules/playwright-core/lib/helper.js:84:31)
          at CRSession.<anonymous> (/Users/jon/dev/qawolf/node_modules/playwright-video/src/ScreencastFrameCollector.ts:40:20)
          at CRSession.emit (events.js:210:5)
          at CRSession.EventEmitter.emit (domain.js:476:20)
          at /Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:137:47
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
      Error: Protocol error (Page.screencastFrameAck): Target closed.
          at /Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:123:63
          at new Promise (<anonymous>)
          at CRSession.send (/Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:122:16)
          at CRSession.<anonymous> (/Users/jon/dev/qawolf/node_modules/playwright-core/lib/helper.js:84:31)
          at CRSession.<anonymous> (/Users/jon/dev/qawolf/node_modules/playwright-video/src/ScreencastFrameCollector.ts:40:20)
          at CRSession.emit (events.js:210:5)
          at CRSession.EventEmitter.emit (domain.js:476:20)
          at /Users/jon/dev/qawolf/node_modules/playwright-core/lib/chromium/crConnection.js:137:47

### PR DESCRIPTION
**Pull request by jperl**
Resolves #12 

- catch and internally log Page.screencastFrameAck

### CODE REVIEW

File: src/ScreencastFrameCollector.ts [hunk 1]
```diff
@@ -51,6 +51,14 @@ export class ScreencastFrameCollector extends EventEmitter {
         received: Date.now(),
         timestamp: payload.metadata.timestamp,
       });
+
+      try {
+        // capture error so it does not propagate to the use
```
Comment (flaurida) [inline src/ScreencastFrameCollector.ts]: typo
